version: 2.1
jobs:
  build:
    docker:
      - image: iatapay/maven-java11-docker-aws-cli
    steps:
      - checkout
      - run:
          name: Build
          command: mvn -B -DskipTests clean package

