version: 2.1

jobs:
  build:
    machine:
      image: ubuntu-2004:202010-01
    steps:
      - checkout
      - run:
          name: Installing AWS CLI
          command: |
            sudo apt-get update
            sudo apt install python3-pip
            sudo pip3 install awsebcli --upgrade
			sudo apt install default-jdk -y
			sudo apt install maven -y
      - run: cd ./app && mvn -B -DskipTests clean package
      - persist_to_workspace:
          root: .
          paths:
            - .

  deploy:
    machine:
        image: ubuntu-2004:202010-01
    steps:
      - attach_workspace:
          at: .
      - checkout
      - run: aws s3 sync ./app/target s3://ci-cd-example-2022
    

workflows:
  build_deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
